apiVersion: v1
kind: Service
metadata:
   name: mongo
   labels:
     run: mongo
spec:
   ports:
     - protocol: TCP
       port: 27017
       targetPort: 27017
   selector:
     run: mongo
---
apiVersion: v1
kind: Deployment
metadata:
   name: mongo
spec:
   template:
     metadata:
       labels:
         run: mongo
     spec:
       containers:
         name: mongo
         image: mongo
         ports:
           containerPort: 27017